### PR TITLE
A few more VERITAS papers; correction to MAGIC HESS J0632+057 2012 papers

### PR DESCRIPTION
**Pull request by GernotMaier**

### CODE REVIEW

**Comment by GernotMaier** [comment]
I don't have permissions to merge. I will add constantly new papers, but prefer to merge at least once a month.

**Comment by cdeil** [comment]
> I don't have permissions to merge.

I'm pretty sure you do. You don't see the green "merge pull request" button at the bottom of pull requests?

> I will add constantly new papers, but prefer to merge at least once a month.

Since we have a second person reviewing the diff of pull requests at the moment (me in this case), it's much easier if you don't continuously add to pull requests, but just make a pull request once in a while when something is ready, and then start a new brach / pull request. I'm merging this now.

**Comment by GernotMaier** [comment]
No green button for me :-(

**Comment by cdeil** [comment]
@GernotMaier - Can you see this page?
https://github.com/gammapy/gamma-cat/settings/collaboration

I can see that you have access there. You had 'write' access, and I changed you to 'admin' 2 days ago, meaning that you can now also set access permissions for others for this repo.

**Pull request merged**
