### PR TITLE
more VERITAS papers; fix of issue #184

### PR DESCRIPTION
**Pull request by GernotMaier**
Pull requests for additional VERITAS data and the fix for issue #184

### CODE REVIEW

**Comment by GernotMaier** [comment]
Note that this pull request did stop with:

"The command "conda update -q conda" failed and exited with 1 during ."

**Comment by cdeil** [comment]
> Note that this pull request did stop with:
> "The command "conda update -q conda" failed and exited with 1 during ."

That was a timeout during conda install (see the line above in the build log).
When that happens you should click the "restart build" button in the top right.
You might have to sign in first (see [here](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI))
For this PR I did restart the build and it passed.

I'll review the changes here now.

**Comment by GernotMaier** [comment]
Ok - units should be cm^2, not m^2. Fixed it.

**Comment by cdeil** [comment]
Thanks!

**Pull request merged**
