### PR TITLE
Data entry for HESS UNID paper 2008A%2526A...477..353A

### PR DESCRIPTION
**Pull request by cdeil**
We should finish data from the HESS UNID source paper.
(cc @adonath, I'm moving an old TODO list to GH issues)

Looks like you added data today, but spectral points are still missing and there should be more sources.
- https://github.com/gammapy/gamma-cat/tree/master/input/papers/2008/2008A%2526A...477..353A
- https://ui.adsabs.harvard.edu/#abs/2008A%26A...477..353A
- http://www.aanda.org/articles/aa/full/2008/49/aa8516-07/aa8516-07.html

I thought we had the spectral points, but now I can't find them in this list:
https://github.com/gammapy/gamma-cat/blob/master/todo/todo_hess_aux.md
and there is no link to auxiliary information at
https://www.mpi-hd.mpg.de/hfm/HESS/pages/publications/pubs_all.shtml

@kosack - Are these spectral points available somewhere? Or could you please provide them? (I mean the points from Figure 8)

### CODE REVIEW

**Comment by cdeil** [comment]
@kosack - I noticed an issue with the spectral points you gave us.

For HESS J1708-410 the paper shows 7 spectral points, with the last at ~ 30 TeV.
The data you provided has 11 points, out to 271.275 TeV:
https://gist.github.com/cdeil/5c728a08572fa3bed09f4d06c47010d2#file-gistfile1-txt-L41

I will now proceed by only taking the first N points, with N determined from the Figure in the paper.

@kosack - Please check and  let us know if this is correct or not!

**Comment by cdeil** [comment]
@kosack - For HESS J1427 you gave 16 points from 0.69 to 50.7 TeV:
https://gist.github.com/cdeil/5c728a08572fa3bed09f4d06c47010d2#file-gistfile1-txt-L1
Figure 8 in the paper has only 8 points, from ~ 1 TeV to ~ 30 TeV.

Can you please check again and send new, correct spectral points?

**Comment by cdeil** [comment]
I've added ECSV spectral points for all 8 sources from the HESS UNID paper here:
https://github.com/gammapy/gamma-cat/pull/30/files

Looks like @adonath already added YAML files for all of them.

So what remains to be done is to wait for @kosack to send correct points for these two sources (see comments above):
- [ ] HESS J1708-410
- [ ] HESS J1427-608

The others seem OK, at least given the number of points and rough energy range.

**Comment by kosack** [comment]
Here are the correct ones I think (E, Flux, E_up, E_down)

1427:
```
1.24608 5.30713e-13     3.33893e-13     3.47539e-13
1.98052 3.59824e-13     1.07417e-13     1.12584e-13
3.19337 1.01253e-13     3.66549e-14     3.90441e-14
5.13902 3.80364e-14     1.3627e-14      1.47479e-14
8.27807 2.43833e-14     6.35792e-15     6.96172e-15
13.3345 2.98488e-15     2.07024e-15     2.37684e-15
21.4796 1.2602e-15      7.95559e-16     9.69592e-16
34.5999 6.32524e-16     3.26976e-16     4.30177e-16
```

1708:
```
0.87858 8.11092e-12     1.27366e-12     1.30268e-12
1.56    1.61977e-12     2.69112e-13     2.76791e-13
2.7675  4.62848e-13     7.40237e-14     7.63878e-14
4.90964 7.2757e-14      2.238e-14       2.3199e-14
8.7023  2.02678e-14     7.85292e-15     8.18445e-15
15.4517 8.66661e-15     2.57528e-15     2.72803e-15
27.3879 1.95119e-15     8.51482e-16     9.25784e-16
48.5872 -1.83443e-16    2.19499e-16     2.51804e-16
86.2707 3.45864e-16     1.35691e-16     1.70504e-16
152.914 6.70363e-16     1.92103e-16     3.16288e-16
271.275 3.62589e-16     2.71942e-16     2.71942e-16
```

**Comment by cdeil** [comment]
@kosack - I don't think those are correct. For 1708 you're again listing a point at 271.275 TeV, but it's not a HESS measurement.

**Comment by kosack** [comment]
that may have been an upper-limit point that doesn't get plotted (At the time there was no functionality to plot ULs).  It's a bit difficult since this was so long ago, I'm not totally certain which files were used and this is even pre-HAP! (wobble_chain's specmaker2 was used) Probably the first few points are correct, and at some point they were no longer plotted/used above a certain energy (based on the significance).

**Comment by cdeil** [comment]
I've updated the 1427 and 1708 points.
This should make the info for this paper complete.
I'm merging this now.

**Comment by cdeil** [comment]
@kosack - In https://github.com/gammapy/gamma-cat/pull/30#issuecomment-262522318 above you said the columns are `(E, Flux, F_up, F_down)`. But I think it's `(E, Flux, Flux_down, Flux_up)`, i.e. the flux up / down column order is different, matching the info you gave previously, no?

If you have time, please check one last time if these points are now correct (`dnde_errn` = `flux_down` and `dnde_errp = flux_up`)!?
- https://github.com/gammapy/gamma-cat/blob/master/input/papers/2008/2008A%2526A...477..353A/tev-000068.ecsv
- https://github.com/gammapy/gamma-cat/blob/master/input/papers/2008/2008A%2526A...477..353A/tev-000093.ecsv

**Pull request merged**
